CREATE DATABASE TESTDB;
USE TESTDB;
CREATE TABLE ACTOR(
ACTOR_ID SMALLINT unsigned primary KEY,
FIRST_NAME VARCHAR(45) NOT NULL,
LAST_NAME VARCHAR(45) NOT NULL);
CREATE TABLE COUNTRY(
COUNTRY_ID SMALLINT unsigned primary KEY,
COUNTRY VARCHAR(50) NOT NULL,
LAST_UPDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE CITY(
CITY_ID SMALLINT UNSIGNED PRIMARY KEY,
CITY VARCHAR(50) NOT NULL,
COUNTRY_ID SMALLINT UNSIGNED, constraint  fk_city_country foreign KEY (COUNTRY_ID)references COUNTRY(COUNTRY_ID),
LAST_UPDATE  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE ADDRESS(
ADDRESS_ID SMALLINT UNSIGNED PRIMARY KEY,
ADDRESS VARCHAR(50) NOT NULL,
ADDRESS2 VARCHAR(50) DEFAULT NULL,
DISTRICT VARCHAR(20) NOT NULL,
CITY_ID SMALLINT UNSIGNED, FOREIGN KEY (CITY_ID)references CITY(CITY_ID),
POSTAL_CODE VARCHAR(10) DEFAULT NULL,
PHONE VARCHAR(20) NOT NULL,
LAST_UPDATE  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
describe address;