use sakila;
select *from actor;
select *from address;
select *from category;
select *from city;
select *from country;
select *from customer;
select *from country where country_id= (select country_id from customer where address_id='5'  and last_update= '2006-02-15 04:57:20');
select * from customer where customer_id='5' and last_update= '2006-02-15 04:57:20';
select count(*) from city where country_id IN (select country_id from  country);
select count(*) from city where country_id > ALL (select country_id from  country);
select count(country_id) from  country;
select * from city;
select * from city where country_id > any(select country_id from country where country between 'A' and 'B');
select * from city where (city_id,country_id) = '5'; (select city_id,country_id from country where country = '5'); 
select city_id,country_id from country where country = '5';
select * from city where exists(select country_id from country); 
select * from payment;
select customer_id, sum(amount) over() from payment;
select datediff(last_update,payment_date) day from payment;
select  payment_id, sum(amount) over(partition by payment_id) Total, avg(amount) over(partition by payment_id) Average, datediff(last_update,payment_date)  Days from payment;
select payment_id, sum(amount) over(partition by customer_id) Total, avg(amount) over(partition by customer_id) Average, amount-avg(amount) over(partition by customer_id) Diff,datediff(last_update,payment_date)  Days from payment;
select payment_id,sum(amount) over(partition by customer_id) total, amount/avg(amount) over(partition by customer_id)*100 as percentage, variance(amount) over(partition by customer_id) as variance,datediff(last_update,payment_date) as days, std(amount) over(partition  by customer_id) as standarddeviation from payment;
select * from payment;
select last_update, year(last_update),count(customer_id) from payment group by last_update order by last_update;
select year(last_update),count(customer_id) from payment group by year(last_update);
select year(payment_date) as year, count(staff_id) as count, sum(count(staff_id)) over (order by payment_date) as running_sum from payment group by year(payment_date) order by year(payment_date);
select year(payment_date) as year, count(customer_id) as count, lag(count(customer_id)) over(order by payment_date) as preview from payment group by year(payment_date) order by year(payment_date);
SET  sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
select payment_id,amount,ntile(4) over( order by amount) as quarters from payment;
select quarters, max(amount) from ( select payment_id,amount,ntile(4) over(order by amount) as quarters from payment) as fan where quarters in(1,4) group by quarters;
select 11.99-2.99;  
select 2.99-(11.99-2.99)*1.5;
select 11.99+(11.99-2.99)*1.5;
select payment_id,amount from payment where amount < 25.490or amount >25.490;
select payment_id,last_update,payment_date, year(last_update) as year,datediff(last_update,payment_date) as Differect, amount, ((amount - lag(amount) over(order by payment_date)) / amount)*100 as growth from payment;
select  payment_date, year(payment_date) as year, count(customer_id) count, lag(count(customer_id)) over(order by payment_date) ,datediff(last_update,payment_date) as difference from payment group by year(payment_date) order by year(payment_date);
select 'Total amount' as parameter , sum(amount) as value from payment where amount union select 'Average amount' as parameter , avg(amount) as value from payment where amount union select 'Minimum amount' as parameter , min(amount) as value from payment where amount union select 'Maximum amount' as parameter , max(amount) as value from payment where amount union select 'variance amount' as parameter , variance(amount) as value from payment where amount;
select payment_id,customer_id,staff_id, sum(amount) over(partition by customer_id) as Total_amount,avg(amount) over(partition by customer_id) as Average_amount, min(amount) over(partition by customer_id) as Minimum_amount from payment;
select payment_date, count(customer_id) as currentcount from payment group by last_update order by last_update;show index from payment;
show index from payment;