use sakila;
select *from payment;
create view money as select payment_id, amount from payment where amount = 2.99;
select * from money;
create view Alls_Total as select 'total amount' as All_Total,sum(amount) as vaLue  from payment union select 'average amount' as All_Total,avg(amount) as vaLue  from payment;
select * from Alls_Total;
create or replace view changes as select * from payment where amount=2.99;
select * from changes;
start transaction;
use employees;
show tables;
select * from employees;
SELECT emp_no, hire_date,gender, case when  hire_date then gender = 'M'  else '9' end gender_found  from employees ;
select emp_no,hire_date, gender,case when gender='M' then concat(first_name,'',last_name)  else 'naku' end FullName  from employees;  # using case function;
select emp_no,hire_date, gender,case when gender='M' then first_name  end Name  from employees;  # using case function;
select hire_date, case when hire_date >1987-03-11 then emp_no else concat(first_name,'',last_name) end name from employees;
select emp_no, case gender when 'F' then hire_date when 'M' then 'Male workers' else 9 end Category from employees;
use employees;
select year(hire_date)as year, count(*)as count from employees where hire_date > '1986-01-01' and  hire_date < '1989-01-01'  group by year(hire_date) order by year(hire_date); 
select sum(case when year(hire_date) = 1986 then 1 else 0 end) year_1986, sum(case when year(hire_date) = 1987 then 1 else 0 end) year_1987,sum(case when year(hire_date) = 1988 then 1 else 0 end) year_1988 from employees  where hire_date > '1986-01-01' and  hire_date < '1989-01-01';  
select * from employees;
select * from titles;
select exists (select 2 from titles where title = 'staff'); 
select exists (select count(*) from titles where title = 'staff');
select exists( select 1 from titles where title = 'begger');
select e.emp_no,e.birth_date,e.first_name,e.last_name, case when exists (select 1 from titles as t where t.title = 'Senior Engineer' and t.emp_no = e.emp_no) then 'come to office' else 'muditu v2la iruu' end working_place from employees as e ;
select e.emp_no,e.title,case when exists (select 1 from titles as t where t.title = 'staff' and t.emp_no = e.emp_no) then 'work from office' else 'work from home' end work_place from titles as e;
use employees;
select * from salaries;
create or replace view sal as select * from salaries where emp_no = '10001';
select * from sal;
insert into sal values (10001,0,'2001-01-02','2002-07-05'),(10001,0,'2002-01-02','2003-07-05'),(10001,0,'2003-01-02','2004-07-05');
select 1000/salary from sal;
select emp_no,salary,1000/case when salary = 0 then 25000 else salary end salary_sharp from sal;
update  sal set salary = case when salary = 0 then 25000 else salary+1000 end;
update sal set salary = case when salary = 25000 then 3500 when from_date = '1987-06-25' then salary+2000 else salary+1000 end; 
use maya;
select * from branch;
select case when br_address is null then '0' when br_address is not null then br_address end br_address from branch;

create Table user_feedback( Id int auto_increment primary key, event_name varchar(55), name varchar(25), properties json, browser json);
desc  user_feedback;
insert into user_feedback values ('1','shopping','Jaya','{ "IP_address": "134.1.141.66" }','{ "Name": " chrome", "os": "android", "resolution":{"x":"5401","y":"892"}}'),
 ('2','mall','Maya','{ "IP_address": "132.1.187.86" }','{"Name": "Relaince","Moblie": "iphone", "resolution":{"x":"1401","y":"1892"}}'),
 ('3','Rounds','Riya','{ "IP_address": "149.1.101.76" }','{"Name": "broswer","laptop": "microsoft", "resolution":{"x":"5401","y":"892"}}');
 update user_feedback set browser = '{ "Name": " firefox", "os": "windows", "resolution":{"x":"5401","y":"892"}}' where id = 3;
 insert into user_feedback values ('4','shopping','Jaya',null,null);
 select * from user_feedback;
 select Id,event_name,name,properties ->> '$.IP_address'as IP_adddres,browser ->>'$.resolution.x'as system_resolution from user_feedback;
 select browser ->>'$.Name' as browser_Name, count(browser) from user_feedback group by browser ->>'$.Name' ; 
 select browser ->>'$.Name' as browser_Name, count(browser) from user_feedback group by browser ->>'$.os' ; 
 insert into user_feedback values ('5','buying','Sakthi','{ "IP_address": "154.1.146.86" }','{ "Name": " chrome", "os": "android", "resolution":{"x":"4401","y":"992"}}');
insert into user_feedback values ('6','wire','mala','{ "IP_address": "164.1.151.00" }','{ "Name": " chrome", "os": "windows", "resolution":{"x":"5401","y":"892"}}');
select json_type('null');
select json_valid('"mala",24');
select json_array('bala', 55, pi());
select json_object('browser_name', 'firefox','resolution','1156*554');
select json_merge_preserve('["mala",23]','{"amount": 5000}');
select json_extract('{"os": "Windows"}', '$.os');
select id,event_name,json_extract(properties,'$.IP_address'), json_extract(browser,'$.os') from user_feedback;
select json_extract ('{"a": "1", "b": "2","c":[5,6,7]}','$.c');
select json_extract('{"a": ("b":1), "c": {"b":2}}','$**.b');
select json_extract('[1,2,3,4,5]','$[1 to 3]');
select json_extract('[1,2,3,4,5]','$[last-3 to last-1]');  